export const GETSONGSDETAIL = 'GETSONGSDETAIL'
export const UPDATESONGSDETAIL = 'UPDATESONGSDETAIL'
export const UPDATEPLAYLIST = 'UPDATEPLAYLIST'
export const UPDATECURRENTSONGINDEX = 'UPDATECURRENTSONGINDEX'
